// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjqB4NR2kw7kcKFTf36nxTupWqov4-ocg',
    appId: '1:658163709332:web:6e0b0ba94f98b770db8b81',
    messagingSenderId: '658163709332',
    projectId: 'yummly-app-a1648',
    authDomain: 'yummly-app-a1648.firebaseapp.com',
    storageBucket: 'yummly-app-a1648.firebasestorage.app',
    measurementId: 'G-5KPM916TWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1-rZzdVMypau9dfi1FGf-9N82CsYHvgU',
    appId: '1:658163709332:android:f425f9371c233ebcdb8b81',
    messagingSenderId: '658163709332',
    projectId: 'yummly-app-a1648',
    storageBucket: 'yummly-app-a1648.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAivurA_0xNSApk4O6wGgtSsDdZFZNSeBg',
    appId: '1:658163709332:ios:6124aa9c58fc3673db8b81',
    messagingSenderId: '658163709332',
    projectId: 'yummly-app-a1648',
    storageBucket: 'yummly-app-a1648.firebasestorage.app',
    iosBundleId: 'com.example.yumly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAivurA_0xNSApk4O6wGgtSsDdZFZNSeBg',
    appId: '1:658163709332:ios:6124aa9c58fc3673db8b81',
    messagingSenderId: '658163709332',
    projectId: 'yummly-app-a1648',
    storageBucket: 'yummly-app-a1648.firebasestorage.app',
    iosBundleId: 'com.example.yumly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjqB4NR2kw7kcKFTf36nxTupWqov4-ocg',
    appId: '1:658163709332:web:05550cd1d5782d98db8b81',
    messagingSenderId: '658163709332',
    projectId: 'yummly-app-a1648',
    authDomain: 'yummly-app-a1648.firebaseapp.com',
    storageBucket: 'yummly-app-a1648.firebasestorage.app',
    measurementId: 'G-NL7VX1D4SL',
  );
}
